### ISSUE TITLE
Ошибка с массивом объектов которые содержат в себе внутри массивы

### ISSUE THREAD

**Issue by 5665tm** [slavniyteo/one-line#10]
Здравствуйте! Спасибо замечательный плагин!
К сожалению в процессе использования столкнулся с проблемой, которую самому быстро не удалось решить.

Есть массив объектов ScenarioItemSpawnerHolder[]
Внутри каждого из ScenarioItemSpawnerHolder есть массив Waves[], на который повешен [OneLine]
В итоге все элементы этого массива обрабатываются как Element 0 и редактируются одновременно

![](https://pp.userapi.com/c840632/v840632258/18ee7/URFm-CMHHp4.jpg)

```
public class MissionGeneratorSettings : ScriptableObject
{
	public ScenarioItemSpawnerHolder[] ScenarioItemSpawners;
}

[Serializable]
public class ScenarioItemSpawnerHolder
{
	public int Length;
	public AnimationCurve Probability;
	public AnimationCurve Multiplier;
	[OneLine]
	public MobWave[] Waves;
}
```

**Comment by slavniyteo** [comment]
Отлично, баги нужно искать. 
Скорее всего, дело в оптимизациях. Завтра посмотрю.

**Comment by slavniyteo** [comment]
Fixed with 231c0f51b69615a4fd278a56a9ae87ac9c1c28ea

Вы можете взять последнюю ревизию, либо дождаться релиза (подожду еще пару багов и выпущу v0.2.1)

**Comment by slavniyteo** [comment]
А нет, нашел граничный случай. Не торопитесь качать последнюю ревизию =)

**Comment by 5665tm** [comment]
спасибо за оперативность!
