### ISSUE TITLE
Некорректные String.Format

### ISSUE THREAD

**Issue by 5665tm** [slavniyteo/one-line#11]
По всему проекту разбросано куча (порядка десятка) неправильных String.Format вида

String.Format("{1} {2}", value1, value2)

Правильно будет:

String.Format("{0} {1}", value1, value2)

Найти можно включив в решарпере отображение таких случаев как ошибок, либо прогнав через PVS Studio (так я на них собственно и наткнулся)

**Comment by slavniyteo** [comment]
Стыд и срам =)

Нашел всего четыре вхождения string.Format. Спасибо.

Fixed in d289064282b5dd80249e95dd572bc4d10b9fb6ff
