### ISSUE TITLE
Problem with new 2018.3 beta

### ISSUE THREAD

**Issue by Mikecoon** [slavniyteo/one-line#30]
So, it looks like something is broken in 2018.3 beta.

Everything is working great in Editor, but when you try to Play, initialize error occurs. 
Seems like, something goes wrong in Initialize function in `Assets\OneLine\OneLine\Editor\Utils\InspectorUtil.cs`

So, in order to work around I found useful to check is `s_CurrentInspectorWindow` really exist and in case of null return false.

So, there are some changes I've made:

```
       public InspectorUtil() {
            enabled = false;
            if (EditorWindow.focusedWindow is PopupWindow) return; // Detect is it [Expandable] popup

            try {
                if (this.Initialize()) // Additional check
                    enabled = true;
            }
            catch (Exception ex){
                Debug.LogError(INITIALIZATION_ERROR_MESSAGE + ex.ToString());
            }
        }

       private bool Initialize(){
            inspectorWindowType = Type.GetType(INSPECTOR_WINDOW_ASSEMBLY_QUALIFIED_NAME);

            // If this field doesn't exist, return false
            if (inspectorWindowType.GetField("s_CurrentInspectorWindow") != null) {
                window = inspectorWindowType
                .GetField("s_CurrentInspectorWindow", BindingFlags.Public | BindingFlags.Static)
                .GetValue(null);    
            } else {
                return false;
            }
            
            scrollPositionInfo = inspectorWindowType.GetField("m_ScrollPosition");
            getWindowPositionInfo = inspectorWindowType.GetProperty("position", typeof(Rect))
                                                        .GetGetMethod();

            var test = ScrollPosition;
            return true;
        }

```

I see that new version is coming, hope this issue would be helpful.

**Comment by slavniyteo** [comment]
Thank you for this bug.

The problem is there: 
- in [2017.3](https://github.com/Unity-Technologies/UnityCsReference/blob/2017.3/Editor/Mono/Inspector/InspectorWindow.cs#L337), the last I've tested, field `s_CurrentInspectorWindow` was `public`;
- in [2018.3b](https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/Inspector/InspectorWindow.cs#L453) `s_CurrentInspectorWindow` is `internal`.

This breaks some _reflection magic_.
I'll fix it in v0.4.0.
