### ISSUE TITLE
Add "how to build" to documentation

### ISSUE THREAD

**Issue by raslab** [slavniyteo/one-line#39]
Yesterday tried to set up locally OneLine project to search how #38 can be fixed. But spend few hours to this :( 
Reasons:
1. I didn't found which version of Unity uses by default for plugin developing
2. When cloned project - not clear then need to clone to assets folder
3. After importing catch some issues with assembly definitions. Problem then in repository references between assembly definitions serialized as GUIDs (not as definitions names) and check needed reference - it's magic)
4. And.... One of missed GUIDs referenced to assembly definition from another repository (rect-ex) )) Maybe will be better to use git submodules functionallity here?

Can you create something like CONTRIBUTING.MD (or just "How to build" paragraph in README.MD) and highlight this things there?

**Comment by slavniyteo** [comment]
Agree with you at this point. I'll do it when I have some time on my hands.

If you check out v0.4.0, it should work as you expect.

At v0.5.0 I adopted OneLine for Unity Package Manager. And now to work with
it you should add cloned OneLine (as file://, not https://) into separate
project with Package Manager.

I'll add CONTRIBUTING.md to explain.

**Comment by slavniyteo** [comment]
I've just written the instruction how to edit OneLine. It's [here](https://github.com/slavniyteo/one-line#edit-oneline-project).

I close the issue, reopen if necessary.

**Comment by raslab** [comment]
Thanks a lot :)
