### ISSUE TITLE
Error: OneLine can not initialize Inspector Window Utility.

### ISSUE THREAD

**Issue by Malkalypse** [slavniyteo/one-line#49]
**General Info**
OS: Windows 10
Unity Version: 2019.4.5f1 Personal
OneLine Version: v0.4.0
OneLine Installation: Assert Store
RectEx Version: # only if changed manually

---

When I select any of the example assets, the following error is printed to the console:

> OneLine can not initialize Inspector Window Utility. 
> You may experience some performance issues. 
> Please create an issue on https://github.com/slavniyteo/one-line/ and we will repair it.
> 
> System.NullReferenceException: Object reference not set to an instance of an object
>   at OneLine.InspectorUtil.Initialize () [0x00011] in C:\Users\Kevin\Documents\Unity\Editor Sandbox\Assets\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:51 
>   at OneLine.InspectorUtil..ctor () [0x00045] in C:\Users\Kevin\Documents\Unity\Editor Sandbox\Assets\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:41 
> UnityEngine.Debug:LogError(Object)
> OneLine.InspectorUtil:.ctor() (at Assets/OneLine/OneLine/Editor/Utils/InspectorUtil.cs:45)
> OneLine.OneLinePropertyDrawer:.ctor() (at Assets/OneLine/OneLine/Editor/OneLinePropertyDrawer.cs:36)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I have just downloaded and installed OneLine for the first time, so I can't say for sure what impact this is having. However, the message told me to post it here, so that's what I am doing.

**Comment by DarkTl** [comment]
Same on 2019.4.18f1

**Comment by slavniyteo** [comment]
Closed with [#v0.5.2](https://github.com/slavniyteo/one-line/releases/tag/v0.5.2)

**Comment by mrmeloman** [comment]
I have it again in 2022.3.16f1
