### ISSUE TITLE
Error When Click on the examples

### ISSUE THREAD

**Issue by ruribev** [slavniyteo/one-line#51]
Hello, I am getting this:

OneLine can not initialize Inspector Window Utility. 
You may experience some performance issues. 
Please create an issue on https://github.com/slavniyteo/one-line/ and we will repair it.

System.NullReferenceException: Object reference not set to an instance of an object
  at OneLine.InspectorUtil.Initialize () [0x00010] in D:\Downloads\UnityVisualModelingFramework\Assets\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:51 
  at OneLine.InspectorUtil..ctor () [0x00039] in D:\Downloads\UnityVisualModelingFramework\Assets\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:41 
UnityEngine.Debug:LogError (object)
OneLine.InspectorUtil:.ctor () (at Assets/OneLine/OneLine/Editor/Utils/InspectorUtil.cs:45)
OneLine.OneLinePropertyDrawer:.ctor () (at Assets/OneLine/OneLine/Editor/OneLinePropertyDrawer.cs:36)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by slavniyteo** [comment]
Hi. What version do you use? 
This issue is resolved in [v0.5.2](https://github.com/slavniyteo/one-line/releases/tag/v0.5.2).

If you get OneLine from Unity Asset Store consider migrate to Package Manager: [installation readme](https://github.com/slavniyteo/one-line#installation)
