### ISSUE TITLE
OneLine can not initialize Inspector Window Utility

### ISSUE THREAD

**Issue by Cat-Vladimiro** [slavniyteo/one-line#52]
OneLine can not initialize Inspector Window Utility. 
You may experience some performance issues. 
Please create an issue on https://github.com/slavniyteo/one-line/ and we will repair it.

System.NullReferenceException: Object reference not set to an instance of an object
  at OneLine.InspectorUtil.Initialize () [0x00010] in D:\Unity Games\*****\Assets\3rd party\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:51 
  at OneLine.InspectorUtil..ctor () [0x00039] in D:\Unity Games\******\Assets\3rd party\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:41 
UnityEngine.Debug:LogError (object)
OneLine.InspectorUtil:.ctor () (at Assets/3rd party/OneLine/OneLine/Editor/Utils/InspectorUtil.cs:45)
OneLine.OneLinePropertyDrawer:.ctor () (at Assets/3rd party/OneLine/OneLine/Editor/OneLinePropertyDrawer.cs:36)
UnityEditor.ScriptAttributeUtility:GetHandler (UnityEditor.SerializedProperty)
UnityEditorInternal.ReorderableList:CacheIfNeeded ()
UnityEditorInternal.ReorderableList:GetListElementHeight ()
UnityEditorInternal.ReorderableList:GetHeight ()
UnityEditorInternal.ReorderableListWrapper:GetHeight ()
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by slavniyteo** [comment]
I guess you've installed One-Line from Unity Asset Store. 

There is a newer version you can get with Unity Package Manager. Instructions are [here](https://github.com/slavniyteo/one-line#installation).
